#!/bin/bash

# Cron script for checking LAN connectivity and restarting the interface

# Ping count is set aggressively to 1, increase depending what you want.
PING_COUNT=1
PING="/bin/ping"


# Find the gateway IP address
GATEWAY_IP=`ip route | grep default | cut -d " " -f 3`
# Ping test
$PING -n -c "$PING_COUNT" "$GATEWAY_IP" &>/dev/null
#if return value is 1 (an error)
if [ "$?" -ge 1 ]
then
    # This will log a message in system log (see manpage).
    logger "Network access DOWN"
    #service network restart
    #change interface name accordingly
    sudo ifup bond0
else
    logger "Network access OK"
fi
